### ISSUE TITLE
Close the application rocketMQTemplate error log.

### ISSUE THREAD

**Issue by yiyuan0109** [apache/rocketmq-spring#136] opened 2019-08-28 10:32 UTC
#https://github.com/apache/rocketmq-spring/issues/93
#Closing the application has the following error:

2019-08-28 18:01:35.623 [Thread-76] DEBUG druid.sql.Statement - {conn-10006, pstmt-20003} closed
2019-08-28 18:01:35.623 [Thread-76] DEBUG druid.sql.Connection - {conn-10006} closed
2019-08-28 18:01:35.639 [Thread-76] INFO  com.alibaba.druid.pool.DruidDataSource - {dataSource-1} closed
2019-08-28 18:01:36.134 [NettyClientSelector_1] INFO  RocketmqRemoting - closeChannel: close the connection to remote address[120.78.171.154:9876] result: true
2019-08-28 18:01:36.236 [NettyClientSelector_1] INFO  RocketmqRemoting - closeChannel: close the connection to remote address[120.78.171.154:10911] result: true
2019-08-28 18:01:36.237 [NettyClientSelector_1] INFO  RocketmqRemoting - closeChannel: close the connection to remote address[120.78.171.154:9876] result: true
2019-08-28 18:01:36.238 [NettyClientSelector_1] INFO  RocketmqRemoting - closeChannel: close the connection to remote address[120.78.171.154:10911] result: true
2019-08-28 18:01:36.237 [Thread-76] INFO  org.springframework.beans.factory.support.DisposableBeanAdapter - Invocation of destroy method failed on bean with name 'rocketMQTemplate'
java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82) ~[?:1.8.0_211]
	at java.lang.Runtime.removeShutdownHook(Runtime.java:239) ~[?:1.8.0_211]
	at org.apache.rocketmq.client.trace.AsyncTraceDispatcher.removeShutdownHook(AsyncTraceDispatcher.java:219) ~[rocketmq-client-4.5.1.jar:4.5.1]
	at org.apache.rocketmq.client.trace.AsyncTraceDispatcher.shutdown(AsyncTraceDispatcher.java:192) ~[rocketmq-client-4.5.1.jar:4.5.1]
	at org.apache.rocketmq.client.producer.DefaultMQProducer.shutdown(DefaultMQProducer.java:302) ~[rocketmq-client-4.5.1.jar:4.5.1]
	at org.apache.rocketmq.spring.core.RocketMQTemplate.destroy(RocketMQTemplate.java:551) ~[rocketmq-spring-boot-2.0.3.jar:2.0.3]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:256) [spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:571) [spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:543) [spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1034) [spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:504) [spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1027) [spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1057) [spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1026) [spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:945) [spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
2019-08-28 18:01:36.242 [Thread-76] INFO  org.springframework.beans.factory.support.DisposableBeanAdapter - Destroy method 'shutdown' on bean with name 'defaultMQProducer' threw an exception
java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82) ~[?:1.8.0_211]
	at java.lang.Runtime.removeShutdownHook(Runtime.java:239) ~[?:1.8.0_211]

#Environment:
  Rocketmq-4.5.2
  Rocketmq-spring-boot-starter-2.0.3

**Comment by chenxubiao** [comment] 2019-09-17 00:36
我也遇到同样的问题。

**Comment by yiyuan0109** [comment] 2019-09-19 08:28
> 我也遇到同样的问题。

我还没有找到解决.

**Comment by RongtongJin** [comment] 2019-09-20 02:15
@yiyuan0109 @chenxubiao The problem is that the JVM is already in the process of shutting down, but the shutdown hook is still being removed manually。You can just ignore this exception. It will be fixed in the future release.

**Comment by vongosling** [comment] 2019-09-28 02:41
https://github.com/apache/rocketmq/pull/1492

**Closed by vongosling** 2019-09-28 02:41 UTC
Labels: bug
